Added Pipelines

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,4 +1,4 @@
-name: Release Workflow
+name: SemVer Release Workflow
 
 run-name: "Releasing ${{ github.event.repository.name }} #${{github.run_number}}"
 
@@ -7,8 +7,8 @@ on:
   workflow_dispatch:
 
 env:
-  BRANCH_NAME: ${{github.ref_name}}
-  TRUNK_BRANCH_NAME: 'main'
+  BRANCH_NAME: ${{ github.ref_name }}
+  TRUNK_BRANCH_NAME: ${{ github.event.repository.default_branch }}
 
 jobs:
   release:
@@ -19,15 +19,39 @@ jobs:
       - name: Verify Branch
         if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
         run: |
-          echo "ERROR: Attempting to release from branch ${{env.BRANCH_NAME}}. Release from ${{env.TRUNK_BRANCH_NAME}} branch only"
+          echo "ERROR: Attempting to release from branch ${{ env.BRANCH_NAME }}. Release from ${{ env.TRUNK_BRANCH_NAME }} branch only."
           exit 1
 
-      - name: Release IKMDEV Code
-        uses: ikmdev/maven-release-action@main
+      - name: Checkout Repository
+        uses: actions/checkout@v4
         with:
-          ikmdevops_pat: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
+          token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
+
+
+      - name: Verify Version
+        run: |
+            CURRENT_VERSION=$(./mvnw help:evaluate -D'expression=project.version' -q -D'forceStdout')
+            CORE_VERSION=$(./mvnw help:evaluate -D'expression=core.artifact.version' -q -D'forceStdout')
+            if [[ "$CURRENT_VERSION" != *"$CORE_VERSION"* ]]; then
+               echo "::error::Current Version Does Not Match Core Version"
+               echo "::error::Current Version: $CURRENT_VERSION"
+               echo "::error::Core Version: $CORE_VERSION"
+               exit 1
+            fi
+
+      - name: Extrapolate IKM Release Property
+        id: newDevVersion
+        run: |
+          CORE_VERSION=$(./mvnw help:evaluate -D'expression=core.artifact.version' -q -D'forceStdout')
+          RC_VERSION=$(./mvnw help:evaluate -D'expression=core.artifact.release' -q -D'forceStdout')
+          RC_NUMBER=$(echo "$RC_VERSION" | grep -o -E '[0-9]+')
+          NEW_RC_NUMBER=$((1 + $RC_NUMBER))
+          echo "DEV_VERSION=$CORE_VERSION-r$NEW_RC_NUMBER-SNAPSHOT" >> $GITHUB_OUTPUT
+
+      - name: Shared Release Action
+        uses: ikmdev/maven-semver-release-action@main
+        with:
+          version_type: 'pre-release'
           github_token: ${{secrets.GITHUB_TOKEN}}
-          ossrh_username: ${{secrets.OSSRH_TOKEN_USER}}
-          ossrh_token: ${{secrets.OSSRH_TOKEN_PASS}}
-          gpg_key: ${{secrets.GPG_KEY}}
-          gpg_passphrase: ${{secrets.GPG_PASSPHRASE}}
+          development_version: ${{steps.newDevVersion.outputs.DEV_VERSION}}
+            
